# сервис базы данных
version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: edi_postgres
    restart: always
    environment:
      POSTGRES_USER: edi_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: edi_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgesql/data

  redis:
    image: redis:7-alpine
    container_name: edi_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

